---
- hosts: all
  remote_user: root
  
  roles: 
    - {role: genlinux, when: ansible_system == "Linux" }
    - {role: redhat, when: ansible_os_family == "RedHat"}
    - {role: debian, when: ansible_os_family == "Debian"}

  tasks:  
    - name: set dracut config
      lineinfile:
        dest: /etc/dracut.conf
        line: add_drivers+="hv_vmbus hv_netvsc hv_storvsc"

    - name: run dracut
      shell: "dracut -f -vf"

    - name: waagent deprovision
      shell: 'waagent -force -deprovision'
      when: ansible_system == "Linux"
    
    - name: Sysprep Win
      raw: "c:\\windows\\system32\\sysprep\\sysprep.exe /oobe /shutdown"
      when: ansible_system == "Win32NT"
      ignore_errors: True #Work-around for the fact that even though this does what it should, ansible considers it a failed task since it loses connection due to the shutdown iniated by syspre.  Will try to find a more elegant solution later.
