---
# tasks file for redhat
  - name: Install libselinux-python
    yum:
      name: libselinux-python
      state: latest

  - name: Apply eth0 ifcfg template
    template: 
      src: templates/ifcfg-eth0.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      owner: root
      group: root
      mode: 0644
  
  - name: Prepare to mod dracut
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - mdadm 
      - cryptsetup 
      - samba-client 
      - samba-common 
      - iscsi-initiator-utils
    when: ansible_distribution_major_version == "7"

#  - name: set dracut config
#    lineinfile:
#      dest: /etc/dracut.conf
#      line: add_drivers+="hv_vmbus hv_netvsc hv_storvsc"
#    when: ansible_distribution_major_version == "7"

#  - name: run dracut
#    shell: "dracut -f -vf"
#    when: ansible_distribution_major_version == "7"

  - name: Add OpenLogic Repo - RHEL/Centos/Oracle Linux 6
    yum_repository:
      name: openlogic
      description: OpenLogic Repo
      baseurl: http://olcentgbl.trafficmanager.net/openlogic/6/openlogic/x86_64/
      gpgcheck: no
      enabled: yes
    when: ansible_distribution_major_version == "6"

  - name: Add OpenLogic Repo - RHEL/Centos/Oracle Linux 7
    yum_repository:
      name: openlogic
      description: OpenLogic Repo
      baseurl: http://olcentgbl.trafficmanager.net/openlogic/7/openlogic/x86_64/
      gpgcheck: no
      enabled: yes
    when: ansible_distribution_major_version == "7"
   
  - name: Install Hyper-V Daemons for VMware VMs
    yum: 
      name: microsoft-hyper-v
      state: latest
    #when: ansible_virtualization_type == "VMware"
  
  - name: start and enable Hyper-V daemons
    service:
      name: hv_kvp_daemon
      state: started
      enabled: true
    #when: ansible_virtualization_type == "VMware"

  - name: Install Azure agent - RHEL/CentOS/Oracle Linux
    yum: name=WALinuxAgent state=present

  - name: Start & Enable waagent - RHEL/Centos
    service: name=waagent state=started enabled=yes
